from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_pdf_report(energy, waste, paper, score, filepath):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    doc    = SimpleDocTemplate(filepath, pagesize=A4)
    styles = getSampleStyleSheet()
    story  = []

    green = colors.HexColor("#16a34a")
    title_style = ParagraphStyle("gh_title", parent=styles["Title"],
                                  textColor=green, fontSize=22, spaceAfter=6)

    story.append(Paragraph("GreenHealth AI — Sustainability Report", title_style))
    story.append(Paragraph(f"Report Date: {datetime.now().strftime('%B %d, %Y at %H:%M')}", styles["Normal"]))
    story.append(Spacer(1, 0.25*inch))

    story.append(Paragraph(
        f"Overall Score: {score['score']}/100  |  Grade: {score['grade']}",
        ParagraphStyle("score", parent=styles["Heading1"], textColor=green)
    ))
    story.append(Spacer(1, 0.2*inch))

    rows = [
        ["Metric", "Today's Value", "Cost (USD)", "Status"],
        ["Energy Usage",   f"{energy['total_kwh']} kWh",     f"${energy['cost_usd']}", "⚡"],
        ["Carbon Emitted", f"{energy['carbon_kg']} kg CO2",  "-",                      "🌍"],
        ["Medical Waste",  f"{waste['total_kg']} kg",         f"${waste['cost_usd']}",  "🏥"],
        ["Hazardous Waste",f"{waste['hazardous_kg']} kg",     "-",                      "⚠️"],
        ["Paper Usage",    f"{paper['total_sheets']} sheets", f"${paper['cost_usd']}",  "📄"],
    ]
    t = Table(rows, colWidths=[2.2*inch, 1.8*inch, 1.4*inch, 0.8*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND",     (0,0), (-1,0),  green),
        ("TEXTCOLOR",      (0,0), (-1,0),  colors.white),
        ("FONTNAME",       (0,0), (-1,0),  "Helvetica-Bold"),
        ("ALIGN",          (0,0), (-1,-1), "CENTER"),
        ("VALIGN",         (0,0), (-1,-1), "MIDDLE"),
        ("GRID",           (0,0), (-1,-1), 0.5, colors.lightgrey),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f0fdf4")]),
        ("FONTSIZE",       (0,0), (-1,-1), 10),
        ("ROWHEIGHT",      (0,0), (-1,-1), 22),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(
        "Generated by GreenHealth AI | Confidential Hospital Sustainability Data",
        ParagraphStyle("footer", parent=styles["Normal"],
                       textColor=colors.grey, fontSize=8)
    ))
    doc.build(story)
    return filepath
